henryproject/api/src/db.js

Corregi user e importe en el archivo db.js para las relaciones

model-users-correciones y relacion en db

---

henryproject/api/src/handlers/getPlataforms.js

mejore la funcion getPlatforms

getPlatforms-mejora

---

henryproject/api/src/db.js
henryproject/api/src/models/Games.js

se modificó la tabla Games

---

henryproject/api/src/handlers/getVideoGamesApi.js

los juegos de la api vienen con la imagen que tengan, a los de la DB por ahora se les agrega una por default

se traen las imagenes con el get a los videjuegos

---

henryproject/api/src/routes/routervideogames.js

se agregó las rutas de get y post

se agregó las rutas de get y post

---

henryproject/api/index.js
henryproject/api/src/handlers/filterRating.js
henryproject/api/src/handlers/getTags.js
henryproject/api/src/routes/routerTags.js

se modificó el index.js

---

henryproject/api/index.js

se modificó index.js

---

henryproject/api/package-lock.json
henryproject/api/package.json
henryproject/api/src/db.js
henryproject/api/src/handlers/mercadopago.js
henryproject/api/src/models/Sale.js
henryproject/api/src/routes/index.js

Se agregó mercado de pago y se modifico el modelo

Se agregó mercado de pago y se modifico el modelo

---

henryproject/Client/src/App.js
henryproject/Client/src/Components/CreateVideogame/EditVideogame/EditVideogame.css
henryproject/Client/src/Components/CreateVideogame/EditVideogame/EditVideogame.jsx
henryproject/Client/src/Components/CreateVideogame/ListVideogame/ListVideogame.jsx
henryproject/Client/src/redux/Reducer/Index.js

avances en componente Crear/Editar

edit component

---

henryproject/Client/src/Components/CreateVideogame/EditVideogame/EditVideogame.css
henryproject/Client/src/Components/CreateVideogame/EditVideogame/EditVideogame.jsx

cambios realizados en componente edit

---

henryproject/Client/src/App.js
henryproject/Client/src/Components/Nav_bar/SignUserModal.jsx
henryproject/api/.env

arregla logout

---

henryproject/Client/src/Components/Games/Games.css
henryproject/Client/src/Components/Games/Games.jsx
henryproject/Client/src/Components/Home/Home.jsx
henryproject/Client/src/Components/Nav_bar/Nav_bar.css
henryproject/Client/src/Components/Nav_bar/Nav_bar.jsx
henryproject/Client/src/Components/SearchBar/SearchBar.css
henryproject/Client/src/Components/SearchBar/SearchBar.jsx

cositas css en nav bar y search

---

henryproject/Client/src/Components/CreateVideogame/CreateVideogame.jsx

ultimos cambios

---

henryproject/api/.env
henryproject/api/src/routes/routervideogames.js

cambios recientes

---

henryproject/Client/src/Components/CreateVideogame/EditVideogame/EditVideogames.css
henryproject/Client/src/Components/CreateVideogame/EditVideogame/EditVideogames.jsx
henryproject/api/.env
henryproject/api/src/handlers/authHandler.js

ultimos cambios en edit videogames

ultimos cambios en edit videogames

---

henryproject/Client/src/Components/SendNews/SendNews.jsx

actualizaciones

---

henryproject/Client/src/Components/CreateVideogame/CreateVideogames.jsx

cambios en validaciones en ingles

cambios en validaciones en ingles

---

henryproject/Client/src/Components/CreateVideogame/EditVideogame/EditVideogames.jsx
henryproject/Client/src/redux/Actions/Index.js
henryproject/Client/src/redux/Reducer/Index.js

se modificó editVideogames

---

henryproject/Client/src/Components/CreateVideogame/EditVideogame/EditVideogames.jsx

cambios en objeto en editvideogames

cambios en objeto en editvideogames

---

henryproject/Client/src/Components/CreateVideogame/EditVideogame/EditVideogames.jsx

se actualizo editVideogames
